### ISSUE TITLE
Desired Count does not scale-down

### ISSUE THREAD

**Issue by pradoz** [MartNoten/docker-ecs-sqs-cdk-autoscaling#1]
Hello,

This tutorial was super helpful, thanks!

When I create 2 events, it raises the Desired Count to 2 and it never seems to go back down. This leaves my ECS service constantly provisioning/deprovisioning two containers which check an empty SQS queue and error out.

Is there any recommended fix for this?

**Comment by pradoz** [comment]
Found a note in the CDK docs [here](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecs.FargateService.html#desiredcount)
> desiredCount?
Type: number (optional, default: When creating the service, default is 1; when updating the service, default uses the current task number.)

**Comment by MartNoten** [comment]
Hi,

Happy to hear you've resolved the matter and thanks for coming back with some documentation. It might help the next person. 

Thanks,
